name: Frontend CI

on:
  push:
    branches: [ develop, main ]
    paths:
      - 'docs/frontend/**'
      - '.github/workflows/ci-frontend.yml'
  pull_request:
    branches: [ develop, main ]
    paths:
      - 'docs/frontend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      working-directory: ./docs/frontend
      run: npm ci
      
    - name: Build
      working-directory: ./docs/frontend
      run: npm run build
      
    - name: Run tests
      working-directory: ./docs/frontend
      run: npm test
